### PR TITLE
Support service command task definitions

### PR DESCRIPTION
**Pull request by tomgoren**
This enables us to update both the service task definition as well as the command task definition.

### CODE REVIEW

**Comment by KensoDev** [comment]
While we are updating this. I think we should move towards a package download as a dependency.
Instead of having this on a *per repo* jarhead copy paste.

**Comment by KensoDev** [comment]
One of the dependencies should be to curl the scripts for the builds. This way.
IMHO, this should be a script that will accept the project name as a param. 

Something like `deploy ${CIRCLE_PROJECT_NAME}`, deploy being something you curl in the beginning of the build.

**Comment by KensoDev** [comment]
Since we need to make changes across the entire project list now, it's a good opportunity to do this.
This will pay off a great deal, allowing us to never change the specific circle.yml file ever again.

**Comment by tomgoren** [comment]
I agree with the sentiment to make wholesale changes less painful in the future - relegating discussion to Tech Design for fear of scope creep.

**Pull request merged**
